### PR TITLE
[WIP] (MODULES-4264) Update for Puppet 4

### PR DESCRIPTION
**Pull request by jeefberkey**
- Updated docs for puppet-strings
- Strongly typed and spec tests pass
- Removed warnings from tests
- Remove old Puppet versions from travis

### CODE REVIEW

**Review by nick-markowski — CHANGES_REQUESTED** [review]
This has a Rakefile that pulls in simp/rake/pupmod/helpers, which in an issue when using the upstream Gemfile

**Review by jeannegreulich — CHANGES_REQUESTED** [review]
When I ran this on Centos 6, postgresql failed because the init.pp params were different.  It did not have the "force" parameter.  Was that left out on purpose?

**Comment by jeefberkey** [comment]
@jeannegreulich The $force parameter doesn't do anything and was deprecated. I removed it in this version, but could add it back.

**Comment by op-ct** [comment]
@jeannegreulich @jeefberkey This was noticed upstream, too: https://github.com/puppetlabs/puppetlabs-postgresql/pull/831

Upstream is waiting to merge the fix _"until we drop Puppet 3 support from puppetlabs-concat, which shouldn't actually be that long:"_ 

----

Happily, a certain @jeefberkey has submitted just such a patch for at GitHub PR   https://github.com/puppetlabs/puppetlabs-concat/pull/424

----
If we aren't able to wait for the upstream sources to merge these, I'd be inclined to merge the  puppetlabs-postgresql PR instead of reverting puppetlabs-concat.

- Puppet ticket for postgresql: https://tickets.puppetlabs.com/browse/MODULES-3328
  - GitHub PR: https://github.com/puppetlabs/puppetlabs-postgresql/pull/831
- Puppet ticket for concat: https://tickets.puppetlabs.com/browse/MODULES-4264
  - GitHub PR: https://github.com/puppetlabs/puppetlabs-concat/pull/424
  - :+1:  Well done, @jeefberkey!

**Comment by jeefberkey** [comment]
This PR contains a version bump, and all modules that use this module will have to get their version requirements bumped. 

However, since it still contains a deprecated parameter and has deviated from my PR upstream, maybe we should make it version 2.99.

**Comment by op-ct** [comment]
If we're using the semantic gem we should be able to do real [semver "pre-release"](http://semver.org/#spec-item-9) tricks, like X.Y.Z-simp6.0.0

**Review by trevor-vaughan — APPROVED** [review]

**Review by nick-markowski — CHANGES_REQUESTED** [review]
Parallel::UndumpableException: RuntimeError:   Error getting RPM info:
     error: line 218: Illegal char '-' (0x2d) in: Version:   2.99.0-simp6

Patching version from -simp to .simp

**Review by nick-markowski — APPROVED** [review]
This looks fine in el7

**Comment by nick-markowski** [comment]
marked as WIP. Slated for first release after 6.0.0-0.

**Comment by jeefberkey** [comment]
Since this didn't get merged in time, the upstream concat module has shown signs of releasing a new version with a few of these commits and official support for Puppet 4. 

Closing this PR.

**Pull request closed without merging**
