### PR TITLE
(MODULES-4264) Update for Puppet 4

### PR DESCRIPTION
**Pull request by jeefberkey**

### CODE REVIEW

**Review by nick-markowski — COMMENTED** [review]
I assume most of this is from upstream? Not sure why the major version bump, but I only did a quick visual CR.  Looks OK.

**Comment by jeefberkey** [comment]
I originally made this change against the upstream repo, and it's a major version bump because it's a Puppet 4 rewrite.

Concat will complain about deprecated validate functions without it.

**Comment by jeefberkey** [comment]
Gotta bring simp-master up to date, that's what all these new commits are

**Comment by jeefberkey** [comment]
Making this PR from a different branch on my repo.

**Pull request closed without merging**
